config/routes.rb
Rails.application.routes.draw do
  root to: 'product_associations#index'
  patch "product_associations/:id/setonline", to: "product_associations#toggle_online", as: "toggle_online"
  resources :graphic_settings, only: [:new, :edit, :update]
  resources :product_associations, only: [:index, :new, :create, :edit, :destroy]
  mount ShopifyApp::Engine, at: '/'

  # Our API (to send info to shopify)
  # constraints format: :json do
  #   get "api/v1/product_associations/:product_id", to: "api/v1/product_associations#products"
  # end
  namespace :api, defaults: { format: :json } do
     namespace :v1 do
      get "product_associations/:product_id", to: "product_associations#products"
     end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product_association.rb
class ProductAssociation < ApplicationRecord
  def self.find_associated_products(shopify_product_id)
    Shop.first.with_shopify!
    ProductAssociation.where(primary_product_id: shopify_product_id.to_s, published: true).map do |associated_product|
      ShopifyAPI::Product.find(associated_product.associated_product_id)
    end
  end
end

app/controllers/api/v1/product_associations_controller.rb
class Api::V1::ProductAssociationsController < Api::V1::BaseController
  # skip_after_action :verify_authorized

  def products
    @product_ids = ProductAssociation.find_associated_products(params[:product_id])
    @shop = Shop.find_by(shopify_domain: request.headers["X-Shopify-Domain"])
  end
end

app/controllers/product_associations_controller.rb
class ProductAssociationsController < AuthenticatedController
  skip_before_action :verify_authenticity_token, :only => [:toggle_online]
  before_action :identify_user

  def index
    @product_associations = ProductAssociation.all
    @products = ShopifyAPI::Product.find(:all)
  end

  def new
    @products = ShopifyAPI::Product.find(:all)
    @webhooks = ShopifyAPI::Webhook.find(:all)
    @product_association = ProductAssociation.new
  end

  def create
    @product_association = ProductAssociation.new(product_association_params)
    if @product_association.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @product_association = ProductAssociation.find(params[:id])
    @product_association.destroy
    # authorize @product_association
    respond_to do |format|
      format.html { redirect_to product_associations_path }
      format.js
    end
  end

  def toggle_online
    @product_association = ProductAssociation.find(params[:id])
    @product_association.published = !@product_association.published
    @product_association.save
    respond_to do |format|
      format.html { redirect_to product_associations_path }
    end
  end

  def identify_user
    @current_shop = ShopifyAPI::Shop.current
    @current_shop_name = @current_shop.name
    @shop_owner_name = @current_shop.shop_owner
    @shop_owner_name_initial = @shop_owner_name.split(" ").map { |x| x.split("").first }.join("")
    @admin_shopify_path = "https://#{@current_shop.domain}/admin/"
  end

  private

  def product_association_params
    params.require(:product_association).permit(:primary_product_id, :associated_product_id)
  end
end

app/views/product_associations/destroy.js.erb
function bundleToRemove() {
  const bundleToRemove = document.getElementById("<%=@product_association.id %>");
  bundleToRemove.remove();
}

bundleToRemove();

app/views/product_associations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <div class="Polaris-Layout__Section Polaris-Layout__Section--secondary">
        <div class="Polaris-Page-Header">
          <div class="Polaris-Card__Header">
            <h2 class="Polaris-Heading">Bundle offers</h2>
          </div>
          <div class="Polaris-Card__Section">
            <%= link_to "New Bundle",  new_product_association_path, class: "btn btn-primary"%>
          </div>
        </div>
      </div>
    </div>

    <div class="col-8">
      <div class="split", style="--top-bar-background:#00848e; --top-bar-color:#f9fafb; --top-bar-background-lighter:#1d9ba4;">
        <div>
          <div class="Polaris-Page">
            <div class="Polaris-Page-Header">
              <div class="Polaris-Page-Header__TitleAndRollup">

                <div class="Polaris-Page__Content">

                  <div class="Polaris-Card">

                    <div class="">
                      <div class="Polaris-DataTable__Navigation"><button type="button" class="Polaris-Button Polaris-Button--disabled Polaris-Button--plain Polaris-Button--iconOnly" disabled="" aria-label="Scroll table left one column"><span class="Polaris-Button__Content"><span class="Polaris-Button__Icon"><span class="Polaris-Icon"><svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
                              <path d="M12 16a.997.997 0 0 1-.707-.293l-5-5a.999.999 0 0 1 0-1.414l5-5a.999.999 0 1 1 1.414 1.414L8.414 10l4.293 4.293A.999.999 0 0 1 12 16" fill-rule="evenodd"></path>
                            </svg></span></span></span></button><button type="button" class="Polaris-Button Polaris-Button--plain Polaris-Button--iconOnly" aria-label="Scroll table right one column"><span class="Polaris-Button__Content"><span class="Polaris-Button__Icon"><span class="Polaris-Icon"><svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
                              <path d="M8 16a.999.999 0 0 1-.707-1.707L11.586 10 7.293 5.707a.999.999 0 1 1 1.414-1.414l5 5a.999.999 0 0 1 0 1.414l-5 5A.997.997 0 0 1 8 16" fill-rule="evenodd"></path>
                            </svg></span></span></span></button>
                      </div>
                      <div class="Polaris-DataTable">
                    <table class="Polaris-DataTable__Table">
                      <thead>
                        <tr>
                          <th data-polaris-header-cell="true" class="Polaris-DataTable__Cell Polaris-DataTable__Cell--header" scope="col" aria-sort="none" style="height: 53px;">Product</th>
                          <th data-polaris-header-cell="true" class="Polaris-DataTable__Cell Polaris-DataTable__Cell--header" scope="col" aria-sort="none" style="height: 53px;">Product 2</th>
                          <th data-polaris-header-cell="true" class="Polaris-DataTable__Cell Polaris-DataTable__Cell--header" scope="col" aria-sort="none" style="height: 53px;">Rates</th>
                          <th data-polaris-header-cell="true" class="Polaris-DataTable__Cell Polaris-DataTable__Cell--header" scope="col" aria-sort="none" style="height: 53px;">Action</th>
                          <th data-polaris-header-cell="true" class="Polaris-DataTable__Cell Polaris-DataTable__Cell--header" scope="col" aria-sort="none" style="height: 53px;">Published</th>
                        </tr>
                      </thead>
                      <tbody>
                        <%@product_associations.each_with_index do |product_association, index| %>
                          <% primary_product = @products.select {|product| product.id == product_association.primary_product_id.to_i } %>
                          <% associated_product = @products.select {|product| product.id == product_association.associated_product_id.to_i } %>
                        <tr class="Polaris-DataTable__TableRow" id="<%= product_association.id %>" style="height: 72px;">
                          <td class="Polaris-DataTable__Cell Polaris-DataTable__Cell" style="height: 72px;"><%= primary_product[0].title %></td>
                          <td class="Polaris-DataTable__Cell Polaris-DataTable__Cell" style="height: 72px;"><%= associated_product[0].title %></td>
                          <td class="Polaris-DataTable__Cell Polaris-DataTable__Cell" style="height: 72px;">Tx conversion 10%,<br> Tx marge 20%</td>
                          <td class="Polaris-DataTable__Cell Polaris-DataTable__Cell" style="height: 72px;">
                           <%= link_to "Supprimer", product_association_path(product_association),class: "btn btn-outline-danger rounded p-2",
                              method: :delete,
                              remote:true,
                              data: {confirm: "are you sure?", product_association_id: product_association.id}%>
                          </td>
                          <td class="Polaris-DataTable__Cell Polaris-DataTable__Cell button" id=<%="onoff"%>, style="height: 72px;">
                            <%= form_for product_association, as: :patch, url: toggle_online_path(product_association), remote:true do |f| %>
                              <input class="tgl tgl-light" id="cb<%=index%>" type="checkbox" name="published" <%= "checked" if product_association.published == true %>></input>
                              <label class="tgl-btn" for="cb<%=index%>"></label>
                              <%= f.submit 'Ready', class:"button_submit d-none" %>
                            <%end %>
                          </td>
                        </tr>
                        <%end%>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<script>
  const online = document.querySelectorAll('input.tgl');
  online.forEach(function(element) {
    element.addEventListener("change", (event) => {
      event.currentTarget.closest("form").querySelector('.button_submit').click()
    });
  });
</script>

app/views/product_associations/new.html.erb
<% content_for :javascript do %>

  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>

<div class="container">
<h1>Select your bundle's products</h1>

<%= simple_form_for(@product_association) do |f| %>

<div class="d-block">
  <div class="d-flex justify-content-around">
    <% (1..2).each do |n|%>
      <%n == 1 ? @param_name = "primary_product_id" : @param_name = "associated_product_id" %>

      <div class="inlist n<%= n %>">
        <% @products.each do |product| %>
          <input type="radio" class="d-none" value="<%= product.id %>" name="product_association[<%= @param_name %>]" id="<%= @param_name%>_<%= product.id %>">
          <label for="<%= @param_name%>_<%= product.id %>">

            <div class="card-product m-3">
              <img src=<%= product.images[0].src %>>

              <div class="card-product-infos d-block">
                <p><%= product.title %></p>
                <p><%= product.variants[0].price %>€</p>
              </div>
            </div>
          </label>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-center">
  <%= f.submit "Create My Bundle", class: "btn btn-primary"  %>
</div>

<% end %>
</div>